# Generated by Django 5.0.2 on 2024-02-16 05:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit', models.IntegerField()),
                ('professor', models.CharField(max_length=250)),
                ('College', models.CharField(choices=[('eng', 'engineering'), ('hum', 'Humanities'), ('med', 'Medical')], max_length=50)),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'FRIDAY')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'none')], max_length=100)),
                ('birth_date', models.DateField()),
                ('id_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$')])),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$')])),
                ('student_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$')])),
                ('password', models.CharField(max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
                ('lessone', models.ManyToManyField(to='selector.lessone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
