# Generated by Django 5.0.2 on 2024-02-10 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_card_number',
        ),
        migrations.AddField(
            model_name='student',
            name='card_number',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator('^\\d$')]),
            preserve_default=False,
        ),
    ]
