# Generated by Django 5.0.2 on 2024-02-16 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lessone",
            new_name="Lesson",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="lessone",
            new_name="lesson",
        ),
    ]
