# Generated by Django 5.0.2 on 2024-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0002_rename_lessone_lesson_rename_lessone_student_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="College",
            field=models.CharField(
                choices=[("eng", "مهندسی"), ("hum", "انسانی"), ("med", "پزشکی")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.CharField(
                choices=[
                    ("SAT", "شنبه"),
                    ("SUN", "یک\u200cشنبه"),
                    ("MON", "دوشنبه"),
                    ("TUES", "سه\u200cشنبه"),
                    ("WED", "چهارشنبه"),
                    ("THUR", "پنج\u200cشنبه"),
                    ("FRI", "جمعه"),
                ],
                max_length=50,
            ),
        ),
    ]
