# Generated by Django 5.0.2 on 2024-02-10 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_rename_birthday_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d$', 'Please enter a card number')]),
        ),
    ]
