# Generated by Django 5.0.2 on 2024-02-14 09:56

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0003_alter_student_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
