# Generated by Django 5.0.2 on 2024-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selector", "0003_alter_lesson_college_alter_lesson_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="College",
            field=models.CharField(
                choices=[
                    ("مهندسی", "مهندسی"),
                    ("انسانی", "انسانی"),
                    ("پزشکی", "پزشکی"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.CharField(
                choices=[
                    ("شنبه", "شنبه"),
                    ("یک\u200cشنبه", "یک\u200cشنبه"),
                    ("دوشنبه", "دوشنبه"),
                    ("سه\u200cشنبه", "سه\u200cشنبه"),
                    ("چهارشنبه", "چهارشنبه"),
                    ("پنج\u200cشنبه", "پنج\u200cشنبه"),
                    ("جمعه", "جمعه"),
                ],
                max_length=50,
            ),
        ),
    ]
