# Generated by Django 5.0.2 on 2024-02-14 10:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0005_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
