# Generated by Django 5.0.2 on 2024-02-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0011_lessone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessone',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selector.student'),
        ),
    ]
