# Generated by Django 5.0.2 on 2024-02-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0012_lessone_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessone',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='lessone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selector.lessone'),
        ),
    ]
