# Generated by Django 5.0.2 on 2024-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0013_remove_lessone_student_student_lessone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lessone',
        ),
        migrations.AddField(
            model_name='student',
            name='lessone',
            field=models.ManyToManyField(to='selector.student'),
        ),
    ]
