# Generated by Django 5.0.2 on 2024-02-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0014_remove_student_lessone_student_lessone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lessone',
            field=models.ManyToManyField(to='selector.lessone'),
        ),
    ]
